version: '3.9'
services :
  frontend:
    image: frontend
    build: ./frontend
    restart : always
    ports:
      - 5173:5173
    depends_on:
      - backend
  backend :
    image: backend
    build: ./backend
    restart : always
    ports :
      - 8888:8888
